images:
  - pull_from: docker.io/grafana/alloy:latest
    push_to: ghcr.io/pmh-only/alloy:latest
    platforms:
      - linux/amd64
      - linux/arm64
    
  - pull_from: docker.io/grafana/grafana-image-renderer:latest
    push_to: ghcr.io/pmh-only/grafana-image-renderer:latest
    platforms:
      - linux/amd64
      - linux/arm64

  - pull_from: docker.io/grafana/grafana:latest
    push_to: ghcr.io/pmh-only/grafana:latest
    platforms:
      - linux/amd64
      - linux/arm64

  - pull_from: docker.io/grafana/loki:latest
    push_to: ghcr.io/pmh-only/loki:latest
    platforms:
      - linux/amd64
      - linux/arm64
      
  - pull_from: docker.io/grafana/tempo:latest
    push_to: ghcr.io/pmh-only/tempo:latest
    platforms:
      - linux/amd64
      - linux/arm64

  - pull_from: docker.io/grafana/mimir:latest
    push_to: ghcr.io/pmh-only/mimir:latest
    platforms:
      - linux/amd64
      - linux/arm64

  - pull_from: docker.io/mongo:latest
    push_to: ghcr.io/pmh-only/mongo:latest
    platforms:
      - linux/amd64
      - linux/arm64

  - pull_from: docker.io/mysql:8
    push_to: ghcr.io/pmh-only/mysql:8
    platforms:
      - linux/amd64
      - linux/arm64
    
  - pull_from: docker.io/redis:alpine
    push_to: ghcr.io/pmh-only/redis:alpine
    platforms:
      - linux/amd64
      - linux/arm64

  - pull_from: docker.io/ghost:alpine
    push_to: ghcr.io/pmh-only/ghost:alpine
    platforms:
      - linux/amd64
      - linux/arm64
      
  - pull_from: docker.io/collabora/code:latest
    push_to: ghcr.io/pmh-only/collabora-code:latest
    platforms:
      - linux/amd64
      - linux/arm64

  - pull_from: docker.io/gitea/gitea:latest
    push_to: ghcr.io/pmh-only/gitea:latest
    platforms:
      - linux/amd64
      - linux/arm64
  
