images:
  - pull_from: docker.io/grafana/grafana-image-renderer:latest
    push_to: ghcr.io/pmh-only/grafana-image-renderer:latest
    platforms:
      - linux/amd64
      - linux/arm64

  - pull_from: docker.io/grafana/grafana:latest
    push_to: ghcr.io/pmh-only/grafana:latest
    platforms:
      - linux/amd64
      - linux/arm64

  - pull_from: docker.io/mongo:latest
    push_to: ghcr.io/pmh-only/mongo:latest
    platforms:
      - linux/amd64
      - linux/arm64

  - pull_from: docker.io/mysql:8
    push_to: ghcr.io/pmh-only/mysql:8
    platforms:
      - linux/amd64
      - linux/arm64

  - pull_from: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0
    push_to: ghcr.io/pmh-only/pgvecto-rs:pg14-v0.2.0
    platforms:
      - linux/amd64
      - linux/arm64
    
  - pull_from: docker.io/redis:alpine
    push_to: ghcr.io/pmh-only/redis:alpine
    platforms:
      - linux/amd64
      - linux/arm64

  - pull_from: docker.io/ghost:alpine
    push_to: ghcr.io/pmh-only/ghost:alpine
    platforms:
      - linux/amd64
      - linux/arm64
      
  - pull_from: docker.io/onlyoffice/documentserver:latest
    push_to: ghcr.io/pmh-only/onlyoffice:latest
    platforms:
      - linux/amd64
      - linux/arm64
      
  - pull_from: docker.io/roundcube/roundcubemail:latest
    push_to: ghcr.io/pmh-only/roundcube:latest
    platforms:
      - linux/amd64
      - linux/arm64
            
  - pull_from: "docker.io/clickhouse/clickhouse-server:25.4.2"
    push_to: ghcr.io/pmh-only/clickhouse-server:rybbit
    platforms:
      - linux/amd64
      - linux/arm64

  - pull_from: docker.io/allinurl/goaccess:latest
    push_to: ghcr.io/pmh-only/goaccess:latest
    platforms:
      - linux/amd64
      - linux/arm64
      
  - pull_from: docker.io/busybox:musl
    push_to: ghcr.io/pmh-only/busybox:latest
    platforms:
      - linux/amd64
      - linux/arm64

  - pull_from: docker.io/machines/filestash:latest
    push_to: ghcr.io/pmh-only/filestash:latest
    platforms:
      - linux/amd64
      - linux/arm64
