name: Mirror Docker Hub images

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  make_batch:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      images: ${{ steps.make_batch.outputs.images }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: make_batch
        run: bash make_batch.sh

  mirror:
    runs-on: ubuntu-latest
    needs: make_batch
    strategy:
      matrix:
        image: ${{ fromJSON(needs.make_batch.outputs.images) }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: bash run.sh ${{ matrix.color }}
